apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  name: demok8-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:      
      labels:
        app: demok8-backend
    spec:
      containers:
      name: demok8-backend
      image: fvoncina/demok8-backend:latest        
      ports:
        containerPort: 5000
      - env:
        - name: NODE_ENV
          value: docker                      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demok8-backend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  - targetPort: 5000
  selector:
    app: demok8-backend