apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: demok8-backend
  name: demok8-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: demok8-backend
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: fvoncina/demok8-backend:latest
        name: demok8-backend
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
